export enum ApiEndpoints {
  SIGN_UP = 'user-service/api/v1/yatri/sign-up',
  LOGIN = 'user-service/api/v1/yatri/login',
  RESET_PASSWORD = 'user-service/api/v1/yatri/reset-password',
  SEND_OTP = 'user-service/api/v1/yatri/send-otp',
  RESEND_OTP = 'user-service/api/v1/yatri/resend-otp',
  PASSWORD_ENCRYPTION_POST = 'user-service/api/v1/password-encryption',
  PHONE_NUMBER_VALIDATE = 'user-service/api/v1/yatri/validate/user-name-phone-number',
  VERIFY_USER_NAME = 'user-service/api/v1/yatri/validate-user/',
  RHF_GET_ALL_STATES = 'health-service/api/v1/state/all',
  RHF_GET_DISTRICT_LIST = 'health-service/api/v1/district/all/state/{stateCode}',
  RHF_GET_FACILITY_LIST = 'health-service/api/v1/healthFacility/all/state/{stateCode}/district/{districtCode}',
  YATRI_UPDATE_DETAILS_POST = 'user-service/api/v1/yatri/update',
  YATRI_GET_ALL_DETAILS_GET = 'user-service/api/v1/yatri/get-user',
  FAQ_URL = 'docs/health/FAQ.json',
  FETCH_MEDICAL_REPORT_GET = 'health-service/api/v1/medical/fetch-medical-report',
  UPDATE_MEDICAL_REPORT_POST = 'health-service/api/v1/medical/save-medical-report',
  GET_ALL_USER_LINKED_WITH_PHONE_NUMBER = 'user-service/api/v1/yatri/phone-number/linked/users/{phoneNumber}',

  // abha creation via aadhar
  ABHA_CREATION_GENERATE_AADHAAR_OTP_POST = 'user-service/api/v1/abha/registration/aadhaar/generateAadhaarOTP',
  ABHA_CREATION_VERIFY_AADHAAR_OTP_POST = 'user-service/api/v1/abha/registration/aadhaar/verifyAadhaarOTP',
  ABHA_VERIFICATION_VERIFY_MOBILE_OTP_POST = 'user-service/api/v1/abha/verification/verifyMobileOTP',
  FETCH_ABHA_CARD = 'user-service/api/v1/abha/registration/fetch/abha-card',
  FETCH_ABHA_CARD_PDF = 'user-service/api/v1/abha/registration/fetch/abha-card-pdf',
  ABHA_CREATION_GENERATE_MOBLIE_OTP_POST = 'user-service/api/v1/abha/registration/aadhaar/generateMobileOTP',
  ABHA_CREATION_VERIFY_MOBILE_OTP_POST = 'user-service/api/v1/abha/registration/aadhaar/verifyMobileOTP',
  CREATE_ABHA_SUGGESTIONS = 'user-service/api/v1/abha/registration/fetch/abha-address-suggestion',
  CREATE_ABHA_ADDRESS = 'user-service/api/v1/abha/registration/create/address',
  //CREATE ABHA VIA IDTP
  USER_INFO_BY_IDTP_GET = 'user-service/api/v1/tourism/getUserInfoByIDTP/{{id}}?consent={{consent}}',
  CREATE_ABHA_AUTH_DEMOGRAPHIC_POST = 'user-service/api/v1/abha/registration/auth-demo',
  GET_STATE_BY_PINCODE = 'user-service/api/v1/utility/pinCode/{{pincode}}',
  // Link ABHA
  LINK_VIA_PHONE_NUMBER_REQUEST_OTP = 'user-service/api/v1/abha/verification/mobile-login-otp',
  LINK_VIA_PHONE_NUMBER_VERIFY_OTP = 'user-service/api/v1/abha/verification/mobile-login-verify',
  LINK_VIA_PHONE_NUMBER_USER_VERIFY = 'user-service/api/v1/abha/verification/user-verify',
  LINK_VIA_AADHAAR_NUMBER_REQUEST_OTP = 'user-service/api/v1/abha/verification/aadhaar-login-otp',
  LINK_VIA_AADHAAR_NUMBER_VERIFY_OTP = 'user-service/api/v1/abha/verification/aadhaar-login-verify',
  LINK_VIA_ABHA_NUMBER_REQUEST_OTP_VIA_AADHAR = 'user-service/api/v1/abha/verification/abha-id/login-otp',
  LINK_VIA_ABHA_NUMBER_REQUEST_OTP_VIA_ABHA = 'user-service/api/v1/abha/verification/abha-id/mobile-login-otp',
  LINK_VIA_ABHA_ADDRESS_REQUEST_OTP_VIA_AADHAR = 'user-service/api/v1/abha/verification/abha-address/login-otp',
  LINK_VIA_ABHA_ADDRESS_REQUEST_OTP_VIA_ABHA = 'user-service/api/v1/abha/verification/abha-address/mobile-login-otp',
  LINK_VIA_ABHA_NUMBER_VERIFY_OTP_VIA_ABHA = 'user-service/api/v1/abha/verification/abha-id/mobile-login-verify',
  LINK_VIA_ABHA_NUMBER_VERIFY_OTP_VIA_AADHAR = 'user-service/api/v1/abha/verification/abha-id/login-verify',
  LINK_VIA_ABHA_ADDRESS_VERIFY_OTP_VIA_ABHA = 'user-service/api/v1/abha/verification/abha-address/mobile-login-otp-verify',
  LINK_VIA_ABHA_ADDRESS_VERIFY_OTP_VIA_AADHAR = 'user-service/api/v1/abha/verification/abha-address/login-otp-verify',
  RECOVER_ABHA_GENERATE_OTP_BY_PHONE_NUMBER = 'user-service/api/v1/abha/verification/forget-abha-otp',
  RECOVER_ABHA_VERIFY_OTP_BY_PHONE_NUMBER = 'user-service/api/v1/abha/verification/forget-abha-verify',
  RECOVER_ABHA_VERIFY_USER = 'user-service/api/v1/abha/verification/forget-user-verify',
}
